# MusicAI
## Sztuczna Inteligencja - projekt 
### Część 4 - Uczenie z klasyfikatorem KNN
Autorzy: Jakub Ochnik, Adam Karabiniewicz, Marcel Bieniek
___

TO-DO: new vector from mfcc

In [1]:
import json
import math
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score 

In [2]:
DATA_PATH = "Data\\data.json"

In [3]:
def load_data(data_path):
    """Loads training dataset from json file.
        :param data_path (str): Path to json file containing data
        :return X (ndarray): Inputs
        :return y (ndarray): Targets
    """

    with open(data_path, "r") as fp:
        data = json.load(fp)

    # convert lists to numpy arrays
    X = np.array(data["mfcc"])
    y = np.array(data["labels"])

    print("Data succesfully loaded!")

    return  X, y

In [4]:
X, y = load_data(DATA_PATH)

Data succesfully loaded!


In [5]:
print(X.shape)

(9996, 130, 13)


In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)

# Convert mfcc to vector 

In [25]:
nsamples_test, nx_test, ny_test = X_test.shape
d2_X_test = X_test.reshape((nsamples_test,nx_test*ny_test))
print(X_test.shape)
print(d2_X_test.shape)

nsamples_train, nx_train, ny_train = X_train.shape
d2_X_train = X_train.reshape((nsamples_train,nx_train*ny_train))
print(X_train.shape)
print(d2_X_train.shape)

(2999, 130, 13)
(2999, 1690)
(6997, 130, 13)
(6997, 1690)


In [26]:
# scaling 
X_sc = StandardScaler()
d2_X_train = X_sc.fit_transform(d2_X_train)
d2_X_test = X_sc.transform(d2_X_test)

In [29]:
k = math.isqrt(len(y_test))
print(k)

54


In [35]:
classifier = KNeighborsClassifier(n_neighbors=k-1)#, metric = 'euclidean')
classifier.fit(d2_X_train, y_train)

y_pred = classifier.predict(d2_X_test)
y_pred

array([5, 0, 6, ..., 6, 9, 9])

In [36]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 84  18   0   1   0 109  62   0   0  14]
 [  0 270   0   0   0  24   1   0   0   0]
 [  1  61  21   0   0 175   9   1   0  46]
 [  2   7   6  41   1 105  47   5   0  67]
 [  1   3  15  16  20 118  84  21   1  23]
 [  0  59   0   0   0 243   2   0   0   0]
 [  1   1   2   0   0  11 278   0   0  11]
 [  0  11   4  10   0  80   0 158   0  24]
 [  0  15   7   3  12 215  12   9  12  25]
 [  4  15   5   6   0 121  42   2   0 119]]


In [40]:
print('Accuracy : ' ,accuracy_score(y_test, y_pred)*100 )
print('F1_score : ' ,f1_score(y_test, y_pred, average='micro')*100)

Accuracy :  41.547182394131376
F1_score :  41.547182394131376
